// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vkugrwvdbqenfsssycfs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZrdWdyd3ZkYnFlbmZzc3N5Y2ZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwNDM2NjcsImV4cCI6MjA2OTYxOTY2N30.1bc0slTt4hbGZ3BwWzRAVD_whEwE14bVN758O8hmwLo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});